In [1]:
print("hello")

hello

In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [11]:
data=pd.read_excel("data\Superstore_Analyzed_Enriched_Demo.xlsx")

In [13]:
data.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,discount,profit,unit_price_estimated,total_cost_estimated,cost_price_per_unit_estimated,reconstructed_sales,sales_reconstruction_error,reconstructed_profit,profit_reconstruction_error,payment_method_simulated
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,41.9136,130.98,220.0464,110.0232,261.9600,0.000000e+00,41.9136,0.000000e+00,Online
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,219.5820,243.98,512.3580,170.7860,731.9400,0.000000e+00,219.5820,0.000000e+00,Debit Card
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,0.00,6.8714,7.31,7.7486,3.8743,14.6200,0.000000e+00,6.8714,0.000000e+00,Online
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.45,-383.0310,348.21,1340.6085,268.1217,957.5775,1.136868e-13,-383.0310,-2.842171e-13,Cash
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.20,2.5164,13.98,19.8516,9.9258,22.3680,0.000000e+00,2.5164,8.881784e-16,Credit Card

In [14]:
data.isnull().sum()

row_id                           0
order_id                         0
order_date                       0
ship_date                        0
ship_mode                        0
customer_id                      0
customer_name                    0
segment                          0
country                          0
city                             0
state                            0
postal_code                      0
region                           0
product_id                       0
category                         0
subcategory                      0
product_name                     0
sales                            0
quantity                         0
discount                         0
profit                           0
unit_price_estimated             0
total_cost_estimated             0
cost_price_per_unit_estimated    0
reconstructed_sales              0
sales_reconstruction_error       0
reconstructed_profit             0
profit_reconstruction_error      0
payment_method_simulated         0
dtype: int64

In [15]:
data.duplicated().sum()

np.int64(0)

In [17]:
data.describe()

,row_id,order_date,ship_date,postal_code,sales,quantity,discount,profit,unit_price_estimated,total_cost_estimated,cost_price_per_unit_estimated,reconstructed_sales,sales_reconstruction_error,reconstructed_profit,profit_reconstruction_error
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9.994000e+03,9994.000000,9.994000e+03
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,55190.379428,229.858001,3.789574,0.156203,28.656896,75.571127,201.201105,53.120197,229.858001,-3.431627e-15,28.656896,-3.982928e-16
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.990000,0.554400,0.544500,0.444000,-9.094947e-13,-6599.978000,-4.547474e-13
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,6.480000,12.688200,3.473600,17.280000,0.000000e+00,1.728750,-8.881784e-16
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,19.980000,41.664000,12.933600,54.490000,0.000000e+00,8.666500,0.000000e+00
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,76.980000,182.226300,54.522000,209.940000,0.000000e+00,29.364000,4.440892e-16
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,7546.160000,24449.558400,4074.926400,22638.480000,4.547474e-13,8399.976000,1.591616e-12
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,188.961461,550.839414,122.251398,623.245101,3.713303e-14,234.260108,3.293513e-14

In [18]:
data.drop(columns=['row_id','sales_reconstruction_error','profit_reconstruction_error'],inplace=True)

In [19]:
data.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,...,sales,quantity,discount,profit,unit_price_estimated,total_cost_estimated,cost_price_per_unit_estimated,reconstructed_sales,reconstructed_profit,payment_method_simulated
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,261.9600,2,0.00,41.9136,130.98,220.0464,110.0232,261.9600,41.9136,Online
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,731.9400,3,0.00,219.5820,243.98,512.3580,170.7860,731.9400,219.5820,Debit Card
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,14.6200,2,0.00,6.8714,7.31,7.7486,3.8743,14.6200,6.8714,Online
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,957.5775,5,0.45,-383.0310,348.21,1340.6085,268.1217,957.5775,-383.0310,Cash
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,22.3680,2,0.20,2.5164,13.98,19.8516,9.9258,22.3680,2.5164,Credit Card